name: 'hal_dbt_poc'
version: '1.0'
config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  hal_dbt_poc:

    raw:
      +database: COMMON_DB_DEV
      +schema: RAW
      +materialized: table

    cleansed:
      +database: COMMON_DB_DEV
      +schema: CLEANSED
      +materialized: table

    presentation:
      +database: COMMON_DB_DEV
      +schema: PRESENTATION
      +materialized: table

seeds:
  hal_dbt_poc:
    +database: COMMON_DB_DEV
    +schema: RAW
