hal_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: dummy
      user: dummy
      password: dummy
      role: DBT_DEV_ROLE
      warehouse: DBT_WH
      database: COMMON_DB_DEV
      schema: PUBLIC
      threads: 4
