hal_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "<account>"
      user: "<user>"
      password: "<password>"
      role: "<role>"
      database: DEV_RAW_DB
      warehouse: "<warehouse>"
      schema: PUBLIC
      threads: 4
