name: Deploy dbt to Snowflake

on:
  push:
    branches:
      - main
    paths:
      - 'Hal_dbt_poc/models/**'
      - 'Hal_dbt_poc/seeds/**'
      - 'Hal_dbt_poc/dbt_project.yml'
      - 'Hal_dbt_poc/packages.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          hal_dbt:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: $SNOWFLAKE_ACCOUNT
                user: $SNOWFLAKE_USER
                password: $SNOWFLAKE_PASSWORD
                role: $SNOWFLAKE_ROLE
                warehouse: $SNOWFLAKE_WAREHOUSE
                database: DEV_RAW_DB
                schema: BASE
                threads: 4
          EOF
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

      - name: Install dbt dependencies
        working-directory: Hal_dbt_poc
        run: dbt deps

      - name: Run dbt Deployment
        working-directory: Hal_dbt_poc
        run: |
          export RAW_DB=DEV_RAW_DB
          export CLEANSED_DB=DEV_CLEANSED_DB
          export MODEL_DB=DEV_MODEL_DB

          export RAW_SCHEMA=RAW
          export CLEANSED_SCHEMA=CLEANSED
          export PRESENTATION_SCHEMA=PRESENTATION

          dbt debug
          dbt seed
          dbt build
