name: HAL - Deploy DBT Project

on:
  push:
    branches:
      - main
    paths:
      - 'Hal_dbt_poc/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.28-linux_x86_64.bash
          bash snowsql-1.2.28-linux_x86_64.bash

      - name: Deploy DBT Project Object
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          snowsql -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER -p $SNOWFLAKE_PASSWORD <<EOF

          USE DATABASE COMMON_DB_DEV;
          USE SCHEMA DBT_PROJECTS;

          CREATE OR REPLACE DBT PROJECT DBTPOC
          FROM GIT REPOSITORY 'HAL_REPO'
          MAIN BRANCH = 'main'
          ROOT_PATH = 'Hal_dbt_poc';

          EOF
